Repository JonayCastro/ets_proyect, pull requests merged in 2025-05, with the labels that each got.

#29 Added button to change password visibility
  app/src/app/components/login/login.component.html
  app/src/app/components/login/login.component.ts
Labels: frontend

#27 Added logout process
  app/src/app/components/navbar/navbar.component.html
  app/src/app/components/navbar/navbar.component.ts
Labels: frontend

#37 Completed readme.md
  README.md
Labels: documentation

#36 Added first version of diagrams
  uml/backend_diagrama.puml
  uml/frontend_diagrama.puml
Labels: documentation

#39 Dockerize application and added .dockerignore to api and app
  .gitignore
  api/.dockerignore
  api/src/main/resources/application-docker.properties
  app/.dockerignore
  app/package.json
  docker-compose.yml
Labels: backend, frontend

#42 Fixed problem to run frontend container
  app/package-lock.json
  app/package.json
  docker-compose.yml
Labels: bug

#47 Created sneaker detail component
  app/angular.json
  app/package-lock.json
  app/src/app/auth/guard/guards.guard.ts
  app/src/app/auth/interceptor/auth.interceptor.ts
  app/src/app/components/sneaker-detail/sneaker-detail.component.html
  app/src/app/components/sneaker-detail/sneaker-detail.component.scss
  app/src/app/components/sneaker-detail/sneaker-detail.component.spec.ts
  app/src/app/components/sneaker-detail/sneaker-detail.component.ts
  app/src/app/components/subscription/subscription.component.ts
  app/src/app/components/user-detail/user-detail.component.html
  app/src/app/components/user-detail/user-detail.component.scss
  app/src/app/components/user-detail/user-detail.component.ts
  app/src/app/dto/sneaker-dto.ts
  app/src/app/interface/sneaker-interface.ts
  app/src/assets/error-img.png
  app/src/assets/generic-sneker-img.jpg
Labels: frontend

#49 Added functionality to get favorites list
  api/src/main/java/com/zeven/ets_proyect/Ets_Proyect/config/ApiMessage.java
  api/src/main/java/com/zeven/ets_proyect/Ets_Proyect/config/ApiPaths.java
  api/src/main/java/com/zeven/ets_proyect/Ets_Proyect/controllers/FavoritesController.java
  api/src/main/java/com/zeven/ets_proyect/Ets_Proyect/dto/sneakers/FavoriteChangedDTO.java
  api/src/main/java/com/zeven/ets_proyect/Ets_Proyect/repositories/FavoriteSneakersRepository.java
  api/src/main/java/com/zeven/ets_proyect/Ets_Proyect/services/FavoriteService.java
  api/src/main/java/com/zeven/ets_proyect/Ets_Proyect/services/UserService.java
  api/src/main/java/com/zeven/ets_proyect/Ets_Proyect/services/impl/FavoriteServiceImpl.java
  api/src/main/java/com/zeven/ets_proyect/Ets_Proyect/services/impl/TelegramNotificationService.java
  api/src/main/java/com/zeven/ets_proyect/Ets_Proyect/services/impl/UserServiceImpl.java
  api/src/main/java/com/zeven/ets_proyect/Ets_Proyect/utils/ScheduledAction.java
  app/src/app/app-routing.module.ts
  app/src/app/app.module.ts
  app/src/app/components/favorite-detail/favorite-detail.component.html
  app/src/app/components/favorite-detail/favorite-detail.component.scss
  app/src/app/components/favorite-detail/favorite-detail.component.spec.ts
  app/src/app/components/favorite-detail/favorite-detail.component.ts
  app/src/app/components/favorites-list/favorites-list.component.html
  app/src/app/components/favorites-list/favorites-list.component.scss
  app/src/app/components/favorites-list/favorites-list.component.spec.ts
  app/src/app/components/favorites-list/favorites-list.component.ts
  app/src/app/components/sidebar/sidebar.component.html
  app/src/app/components/sneakers-list/sneakers-list.component.ts
  app/src/app/config/paths.ts
  app/src/app/dto/favorite-dto.ts
  app/src/app/interface/favorite-interface.ts
  app/src/app/services/favorite/favorites.service.spec.ts
  app/src/app/services/favorite/favorites.service.ts
Labels: backend, frontend

#54 Added process to delete favorites
  api/src/main/java/com/zeven/ets_proyect/Ets_Proyect/config/ApiPathVariables.java
  api/src/main/java/com/zeven/ets_proyect/Ets_Proyect/config/ApiPaths.java
  api/src/main/java/com/zeven/ets_proyect/Ets_Proyect/controllers/FavoritesController.java
  app/src/app/components/favorite-detail/favorite-detail.component.html
  app/src/app/components/favorite-detail/favorite-detail.component.ts
  app/src/app/components/favorites-list/favorites-list.component.ts
  app/src/app/components/sneaker-detail/sneaker-detail.component.ts
  app/src/app/config/app-constants.ts
  app/src/app/config/paths.ts
  app/src/app/emitters/favorite-emiter/favorites-emiter.service.ts
  app/src/app/services/favorite/favorites.service.ts
Labels: backend, frontend

#58 Feature/filter results
  api/src/main/java/com/zeven/ets_proyect/Ets_Proyect/config/ApiPaths.java
  api/src/main/java/com/zeven/ets_proyect/Ets_Proyect/controllers/FavoritesController.java
  api/src/main/java/com/zeven/ets_proyect/Ets_Proyect/controllers/SneakersController.java
  api/src/main/java/com/zeven/ets_proyect/Ets_Proyect/dto/FilterDTO.java
  api/src/main/java/com/zeven/ets_proyect/Ets_Proyect/repositories/FavoriteSneakersRepository.java
  api/src/main/java/com/zeven/ets_proyect/Ets_Proyect/repositories/SneakerRepository.java
  api/src/main/java/com/zeven/ets_proyect/Ets_Proyect/services/FavoriteService.java
  api/src/main/java/com/zeven/ets_proyect/Ets_Proyect/services/SupplierCatalogServices.java
  api/src/main/java/com/zeven/ets_proyect/Ets_Proyect/services/impl/FavoriteServiceImpl.java
  api/src/main/java/com/zeven/ets_proyect/Ets_Proyect/services/impl/SneakersCatalogService.java
  app/src/app/app.module.ts
  app/src/app/components/dashboard/dashboard.component.html
  app/src/app/components/favorites-list/favorites-list.component.html
  app/src/app/components/favorites-list/favorites-list.component.ts
  app/src/app/components/filter/filter.component.html
  app/src/app/components/filter/filter.component.scss
  app/src/app/components/filter/filter.component.spec.ts
  app/src/app/components/filter/filter.component.ts
  app/src/app/components/navbar/navbar.component.ts
  app/src/app/components/sidebar/sidebar.component.html
  app/src/app/components/sidebar/sidebar.component.scss
  app/src/app/components/sneakers-list/sneakers-list.component.html
  app/src/app/components/sneakers-list/sneakers-list.component.ts
  app/src/app/components/subscription/subscription.component.ts
  app/src/app/config/app-constants.ts
  app/src/app/config/filters/filter-types.ts
  app/src/app/config/filters/filter.ts
  app/src/app/config/paths.ts
  app/src/app/dto/filters-dto.ts
  app/src/app/emiters/favorite-emiter/favorites-emiter.service.spec.ts
  app/src/app/emiters/favorite-emiter/favorites-emiter.service.ts
  app/src/app/emitters/favorite-emiter/favorites-emiter.service.ts
  app/src/app/emitters/filter-emitter/filters-emitter.service.spec.ts
  app/src/app/emitters/filter-emitter/filters-emitter.service.ts
  app/src/app/enums/filter-events.ts
  app/src/app/interface/filters-interface.ts
  app/src/app/services/filtered-search/filtered-search.service.spec.ts
  app/src/app/services/filtered-search/filtered-search.service.ts
Labels: backend, frontend

#60 Mostrar ofertas y filtrar
  api/src/main/java/com/zeven/ets_proyect/Ets_Proyect/config/ApiPaths.java
  api/src/main/java/com/zeven/ets_proyect/Ets_Proyect/controllers/FavoritesController.java
  api/src/main/java/com/zeven/ets_proyect/Ets_Proyect/dto/sneakers/OffersDTO.java
  api/src/main/java/com/zeven/ets_proyect/Ets_Proyect/repositories/FavoriteSneakersRepository.java
  api/src/main/java/com/zeven/ets_proyect/Ets_Proyect/services/FavoriteService.java
  api/src/main/java/com/zeven/ets_proyect/Ets_Proyect/services/impl/FavoriteServiceImpl.java
  api/src/main/java/com/zeven/ets_proyect/Ets_Proyect/services/impl/TelegramNotificationService.java
  api/src/main/java/com/zeven/ets_proyect/Ets_Proyect/utils/ScheduledAction.java
  app/package-lock.json
  app/src/app/app-routing.module.ts
  app/src/app/app.module.ts
  app/src/app/components/offers-detail/offers-detail.component.html
  app/src/app/components/offers-detail/offers-detail.component.scss
  app/src/app/components/offers-detail/offers-detail.component.spec.ts
  app/src/app/components/offers-detail/offers-detail.component.ts
  app/src/app/components/offers-list/offers-list.component.html
  app/src/app/components/offers-list/offers-list.component.scss
  app/src/app/components/offers-list/offers-list.component.spec.ts
  app/src/app/components/offers-list/offers-list.component.ts
  app/src/app/components/sidebar/sidebar.component.html
  app/src/app/config/paths.ts
  app/src/app/dto/offers-dto.ts
  app/src/app/interface/offers-interface.ts
  app/src/app/services/filtered-search/filtered-search.service.ts
  app/src/app/services/offers/offers.service.spec.ts
  app/src/app/services/offers/offers.service.ts
Labels: backend, frontend

#66 Fixed permissions problems
  docker-compose.yml
Labels: bug, docker

#68 Cambio de paleta de color
  app/src/app/components/dashboard/dashboard.component.scss
  app/src/app/components/favorite-detail/favorite-detail.component.scss
  app/src/app/components/favorites-list/favorites-list.component.scss
  app/src/app/components/filter/filter.component.html
  app/src/app/components/filter/filter.component.scss
  app/src/app/components/login/login.component.scss
  app/src/app/components/navbar/navbar.component.scss
  app/src/app/components/offers-detail/offers-detail.component.scss
  app/src/app/components/offers-list/offers-list.component.scss
  app/src/app/components/sidebar/sidebar.component.html
  app/src/app/components/sidebar/sidebar.component.scss
  app/src/app/components/sneaker-detail/sneaker-detail.component.scss
  app/src/app/components/sneakers-list/sneakers-list.component.scss
  app/src/app/components/subscription/subscription.component.scss
  app/src/styles/_variables.scss
Labels: frontend

#70 Corrected layout
  app/src/app/components/favorite-detail/favorite-detail.component.scss
  app/src/app/components/login/login.component.scss
  app/src/app/components/offers-detail/offers-detail.component.scss
  app/src/app/components/sidebar/sidebar.component.scss
  app/src/app/components/sneaker-detail/sneaker-detail.component.scss
  app/src/app/components/subscription/subscription.component.scss
  app/src/styles/_variables.scss
Labels: bug, frontend

#72 Show real image sneakers
  api/src/main/java/com/zeven/ets_proyect/Ets_Proyect/dto/sneakers/OffersDTO.java
  api/src/main/java/com/zeven/ets_proyect/Ets_Proyect/repositories/FavoriteSneakersRepository.java
  app/src/app/components/favorite-detail/favorite-detail.component.html
  app/src/app/components/favorite-detail/favorite-detail.component.ts
  app/src/app/components/offers-detail/offers-detail.component.html
  app/src/app/components/offers-detail/offers-detail.component.scss
  app/src/app/components/offers-detail/offers-detail.component.ts
  app/src/app/components/sneaker-detail/sneaker-detail.component.html
  app/src/app/components/sneaker-detail/sneaker-detail.component.ts
  app/src/app/config/app-constants.ts
  app/src/app/dto/offers-dto.ts
  app/src/app/interface/offers-interface.ts
Labels: frontend
